services:
  _defaults:
    autowire: true
    autoconfigure: true  
    public: false

  n1ebieski.customergrouplevels.customergroupcategory_repository:
    class: N1ebieski\CustomerGroupLevels\Repository\CustomerGroupCategory\CustomerGroupCategoryRepository
    public: true
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - N1ebieski\CustomerGroupLevels\Entity\CustomerGroupCategory\CustomerGroupCategory   

  n1ebieski.customergrouplevels.customergroupcategory_staticcache:
    class: N1ebieski\CustomerGroupLevels\StaticCache\CustomerGroupCategory\CustomerGroupCategoryStaticCache
    public: true  
    arguments:
      - '@n1ebieski.customergrouplevels.customergroupcategory_repository'