imports:
  - { resource: ./common.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true  
    public: false

  kernel.listener.prefix:
    class: N1ebieski\CustomerGroupLevels\EventListener\TablePrefixEventListener
    arguments:
      - '%database_prefix%'
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata, method: loadClassMetadata }

  n1ebieski.customergrouplevels.admin_customer_category_type:
    class: N1ebieski\CustomerGroupLevels\Form\Type\Admin\Customer\CategoryType
    public: true
    tags:
      - { name: form.type }

  n1ebieski.customergrouplevels.customergroupcategory_entity:
    class: N1ebieski\CustomerGroupLevels\Entity\CustomerGroupCategory\CustomerGroupCategory
    shared: false

  n1ebieski.customergrouplevels.customergroupcategory_service:
    class: N1ebieski\CustomerGroupLevels\Service\CustomerGroupCategory\CustomerGroupCategoryService
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@n1ebieski.customergrouplevels.customergroupcategory_entity'